### PR TITLE
Transistion to python 3

### PR DESCRIPTION
**Pull request by tomkooij**
This is a port of the datastore to python 3.

~~tl;dr: It is not safe to merge this without (more) testing!~~

Although conversion is trivial, there are two major points to consider:
 - python 3 treats bytestring and strings very different from python 2. **Blobs are bytestrings** and stored as such. SAPPHiRE already deals with this.
 - **python 2 pickles are not readable in python 3**. This basically breaks the entire datastore. See note below.

Due to the above caveats I have implemented some acceptance tests for both the writer and the WSGI app. These tests are certainly not unittests: I push something in and see what comes out. These tests were necessary, because things did break. The writer lacks coverage, but I feel critical py2<>py3 conversion parts are covered.

ToDo:
 - [x] 2to3 conversion
 - [x] Add tests for the WSGI app. (Using WebTest, so we don't need uWSGI)
 - [x] Add tests for the writer. Tests `process_data()`, not the writer main loop. Not all uploadcodes are tested. 
 - [x] Add python 3 pickles to acceptance tests for the writer.
 - [x] Add tests to travis
 - [x] Add coverage [Coverage Status](https://coveralls.io/github/tomkooij/datastore?branch=datastore_py3)
 - [x] Test basic behavior in VM: the `send_fake_events.py` script works.
 - [x] Test real live behavior in VM. Gather some (a lot?) real data and push into the VM. Check against py2 version.
 - [x] 2to3 `examples/datastore-config-server.py` (in provisioning as well)

Notes about the unpickling mess:
  - CPython 3 (py3) cannot read the CPython 2 (py2) protocol 0 pickles... Fortunately, I already dealt with this mess when doing the SAPPHiRE py2to3 conversion. (Fixed in PyTables).
  - py3 can write protocol 0 (py2) pickles, but even those are unreadable in py3. At least that is consistent.
  - py2 cannot read the default protocol used in py3.

When python 3 (the datastore) reads a py2 pickle (from a station), `pickle` will throw `UnicodeDecodeError`, because the unpickled object is incompatible with `utf-8`. sigh. CPython 3.3 added `latin-1` encoding which unpickled most objects succesfully, however `datetime` still fails, throwing a `TypeError`. Did I say, sigh? CPython 3.4 added `bytes` encoding which basically leaves all strings as bytestring. Including dictonary keys (everything in `__dict__`). So that breaks everything.

To solve, we do this:
```
try:
   data = pickle.load(f)
except UnicodeDecodeError:
   data = decode_object(pickle.load(f, encoding='bytes'))
```
`decode_object()` recursively decodes all bytestring to strings. (Including things that actually are bytestrings, such as blobs. Because of base64 encoding of the blobs, we can safely do this.

### CODE REVIEW

**Comment by davidfokkema** [comment]
Wait. Is it impossible for Python 3 to read python 2 pickles? Or just inconvenient? From your comments, I gather it is the latter.

**Comment by tomkooij** [comment]
Inconvenient for our data. Next to impossible for `class`es with `datetime.datetime`. Impossible for most numpy stuff.

http://bugs.python.org/issue6784

**Comment by davidfokkema** [comment]
Hm.

**Comment by tomkooij** [comment]
I agree. But I haven't moved it out of provisioning. That was the initial plan. But I decided against the extra work involved. This is just an example.

The real script is in HiSPARC/publicdb@2f08251

I could still let this script read configs, but that's too much work. I'll add config variables in the script:

``` 
DATASTORE_URL = 
```

**Comment by davidfokkema** [comment]
Ah, ok! Just an example, I missed that.

**Comment by tomkooij** [comment]
This is done. This should be safe for usage on frome.

**Comment by 153957** [comment]
Out of curiosity; is pickling the other way fully compatible? i.e. Python 3 pickles can be unpickled by Python 2?

**Comment by tomkooij** [comment]
@153957: py2 cannot read the default py3 protocol, but you can use the python 2 default protocol on py3:

```
pickle.dump(obj, f, protocol=0)
```

**Comment by davidfokkema** [comment]
Is this currently running on the server?

**Comment by tomkooij** [comment]
No... (the previous master wasn't, I tagged the version that is currently running on frome as `frome-pre2017`). Frome still needs to be upgraded, but we intend to install this version if we do upgrade frome.

**Comment by davidfokkema** [comment]
Ok.

**Pull request merged**
